export type Exercise = { id:string; name:string; muscle:string; group:string; equipment:string; sets:number; reps:string; previous:string; cue:string; gif?:string };
export const exercises: Exercise[] = [
 {id:'bench',name:'Barbell bench press',muscle:'Chest',group:'Push',equipment:'Barbell',sets:4,reps:'6–8',previous:'82.5 kg × 8 · 8 · 7',cue:'Keep shoulder blades set and drive through the floor.'},
 {id:'row',name:'Chest-supported row',muscle:'Back',group:'Pull',equipment:'Dumbbell',sets:3,reps:'8–10',previous:'30 kg × 10 · 10 · 9',cue:'Pull elbows toward your back pockets; pause at the top.'},
 {id:'squat',name:'High-bar back squat',muscle:'Quads',group:'Legs',equipment:'Barbell',sets:4,reps:'5–7',previous:'100 kg × 6 · 6 · 5',cue:'Brace before every rep and keep the descent controlled.'},
 {id:'rdl',name:'Romanian deadlift',muscle:'Hamstrings',group:'Legs',equipment:'Barbell',sets:3,reps:'8–10',previous:'85 kg × 9 · 8 · 8',cue:'Hinge until the hamstrings load; keep the bar close.'},
 {id:'lat',name:'Neutral-grip pulldown',muscle:'Lats',group:'Pull',equipment:'Cable',sets:3,reps:'8–12',previous:'55 kg × 11 · 10 · 10',cue:'Lead with the elbows and avoid swinging.'},
 {id:'lateral',name:'Cable lateral raise',muscle:'Delts',group:'Push',equipment:'Cable',sets:3,reps:'12–15',previous:'7.5 kg × 14 · 13 · 12',cue:'Move through the shoulder, not the trap.'},
 {id:'curl',name:'Incline dumbbell curl',muscle:'Biceps',group:'Pull',equipment:'Dumbbell',sets:3,reps:'10–12',previous:'12 kg × 12 · 11 · 10',cue:'Let the arm lengthen; keep the upper arm still.'},
 {id:'split',name:'Rear-foot elevated split squat',muscle:'Glutes',group:'Legs',equipment:'Dumbbell',sets:3,reps:'8–10 / side',previous:'20 kg × 9 · 9 · 8',cue:'Own the bottom position and push through the whole foot.'}
];
export type LoggedSet = { exerciseId:string; set:number; weight:number; reps:number; done:boolean };
export type AppState = { onboarded:boolean; mode:'GUIDED'|'PERFORMANCE'|'COACH'; activeWorkout:boolean; completed:number; logged:LoggedSet[]; weights:number[]; lastReview?:string };
export const initialState:AppState = { onboarded:true, mode:'GUIDED', activeWorkout:false, completed:3, logged:[], weights:[79.6,79.4,79.7,79.2,79.1,78.9,78.8] };
export function nextLoad(e:Exercise, reps:number, rir:number, model='DOUBLE PROGRESSION'){ if(model==='MANUAL') return {load:'Keep current load',reason:'Manual progression is on.'}; if(reps>=Number(e.reps.split('–')[1] ?? 12) && rir>=2) return {load:'+2.5 kg',reason:`You hit the top of ${e.reps} with RIR ${rir}.`}; if(rir<=0) return {load:'Keep current load',reason:'Last set reached failure; earn the next jump with cleaner reps.'}; return {load:'Add 1 rep',reason:`Stay inside ${e.reps} and build another exposure before adding load.`}; }
export function trend(values:number[]){ if(!values.length) return null; const recent=values.slice(-7); const avg=recent.reduce((a,b)=>a+b,0)/recent.length; const first=recent[0]; const delta=avg-first; return {avg:Number(avg.toFixed(1)),delta:Number(delta.toFixed(1)),direction:delta<-.1?'down':delta>.1?'up':'steady'} as const; }
export function getNextAction(s:AppState){ if(!s.onboarded) return {title:'Finish your setup',why:'Your goal and schedule are the only missing inputs.',cta:'Set up BODYMADE',kind:'setup'}; if(s.activeWorkout) return {title:'Continue your session',why:'Your last set is saved locally and ready when you are.',cta:'Resume workout',kind:'resume'}; if(s.completed===0) return {title:'Start your first session',why:'A simple full-body start gives BODYMADE enough signal to personalize your plan.',cta:'Start Day 1',kind:'start'}; return {title:'Upper A is ready',why:'It is Thursday and Upper A is next in your 3-day plan.',cta:'Start workout',kind:'start'}; }
