export type EvidenceLevel='high'|'moderate'|'low'|'heuristic';
export type EvidenceRule={id:string;topic:string;rationale:string;evidenceLevel:EvidenceLevel;applicablePopulation:string;source:string;reviewedAt:string};
export const evidenceRegistry:EvidenceRule[]=[
 {id:'RT-CONSISTENCY-2026',topic:'resistance-training',rationale:'Prefer a sustainable, goal-matched plan and allow users to select exercises and equipment. BODYMADE does not prescribe an individualized clinical program.',evidenceLevel:'high',applicablePopulation:'Generally healthy adults; adapt for individual medical needs.',source:'ACSM 2026 Resistance Training Position Stand overview',reviewedAt:'2026-09-27'},
 {id:'PA-WHO-2020',topic:'physical-activity',rationale:'WHO guidance for adults is 150–300 minutes of moderate aerobic activity, 75–150 minutes vigorous activity, or an equivalent combination weekly. BODYMADE records no automatic compliance score.',evidenceLevel:'high',applicablePopulation:'Adults; recommendations differ for some age and clinical groups.',source:'WHO Guidelines on Physical Activity and Sedentary Behaviour',reviewedAt:'2026-09-27'},
 {id:'WEIGHT-TREND-01',topic:'body-weight-trend',rationale:'Use multiple measurements to reduce the influence of one noisy reading. Current display averages two halves of up to 14 readings; this is descriptive and is not an expenditure or coaching model.',evidenceLevel:'heuristic',applicablePopulation:'Adults who choose to track body mass.',source:'BODYMADE internal calculation; no external claim',reviewedAt:'2026-09-27'},
 {id:'E1RM-EPLEY-01',topic:'strength-estimation',rationale:'Epley estimate load × (1 + repetitions / 30) is displayed as a rough estimate from logged sets, not a measured one-repetition maximum.',evidenceLevel:'heuristic',applicablePopulation:'Submaximal resistance sets; estimate is less useful at high repetitions and varies by person.',source:'Epley, Boyd (1985), Poundage Chart; original coaching chart, not a peer-reviewed validation study',reviewedAt:'2026-09-27'},
 {id:'READINESS-HOLD-01',topic:'readiness',rationale:'Do not issue a numeric readiness score without an adequate personal baseline and relevant signals.',evidenceLevel:'heuristic',applicablePopulation:'All users; no numeric readiness score is currently calculated.',source:'BODYMADE product safety rule',reviewedAt:'2026-09-27'},
];
